Added t option for switch off of time stamp

diff --git a/show b/show
--- a/show
+++ b/show
@@ -2,7 +2,7 @@
 
 # Function for printing messeage or command's output in various ways
 # USAGE:
-#    show.sh "messeage" [option]
+#    show "messeage" [option]
 # OPTIONS:
 #       [no option] - verbose mode on (print output to both terminal and to log)
 #       v - turn off verbose (print messeage only to log)
@@ -10,6 +10,12 @@
 #       w - warning (print messeage in red color to both terminal and log but stil continue)
 #       y - print standard messeage in yellow color
 #       g - print standard messeage in green color
+#       t - switch off time mark
+# EXAMPLE USAGE:
+#       show "Hello world" g    - print "Hello world" in green color to both terminal and log with time stamp
+#       show "Hello world" gt   - print "Hello world" in green color to both terminal and log without time stamp
+#       show "Hello world" v    - print "Hello world" only to log (verbose off) with time stamp
+#       show "Hello world" vt    - print "Hello world" only to log (verbose off) without time stamp
 
 # IMPORTANT: This funtion collaborates with exe function
 
@@ -38,33 +44,45 @@ trap_exit()
     fi
 }
 
+# Switch off time mark
+if [[ $2 =~ "t" ]]; then
+
+    print_date=""
+
+else
+
+    print_date="$(date "+%T_%Y-%m-%d"): "
+
+fi
+
+
 # ERROR - print messeage in red color to both terminal and log with time stamp and exit
 if [[ $2 =~ "e" ]]; then
 
-        echo -e "${red}$(date "+%T_%Y-%m-%d"): ERROR: $1\nExiting...${normal}" 1>&2
+        echo -e "${red}${print_date}ERROR: $1\nExiting...${normal}" 1>&2
         trap_exit
 
 # WARNING - print messeage in red color to both terminal and log  with time stamp but stil continue
 elif [[ $2 =~ "w" ]]; then
 
-        echo -e "${red}$(date "+%T_%Y-%m-%d"): WARNING: $1\nContinuing...${normal}" 1>&2
+        echo -e "${red}${print_date}WARNING: $1\nContinuing...${normal}" 1>&2
 
 # Standard messeage in yellow color to both terminal and log with time stamp
 elif [[ $2 =~ "y" ]]; then
 
-        echo -e "${yellow}$(date "+%T_%Y-%m-%d"): $1${normal}" 1>&2
+        echo -e "${yellow}${print_date}${1}${normal}" 1>&2
 
 # Standard messeage in green color to both terminal and log with time stamp
 elif [[ $2 =~ "g" ]]; then
 
-        echo -e "${green}$(date "+%T_%Y-%m-%d"): $1${normal}" 1>&2
+        echo -e "${green}${print_date}${1}${normal}" 1>&2
 
-# NO OPTION - output from command or message to screen and to log (= verbose mode) without time stamp
+# NO OPTION - output from command or message to screen and to log (= verbose mode)
 elif [[ ! ( $2 =~ "v" ) ]]; then
 
         # Messeage
         if [[ "$1" != "--stdin" ]]; then
-                echo -e "$1"
+                echo -e "${print_date}${1}"
         # Command
         else
             while read line; do
@@ -82,7 +100,7 @@ elif [[ $2 =~ "v" ]]; then
 
         # Messeage
         if [[ "$1" != "--stdin" ]]; then
-                echo -e "$1" >> $LOGPATH
+                echo -e "${print_date}${1}" >> $LOGPATH
         # Command
         else
                 while read line; do
